# Dataset configuration
dataset:
  train_file: "../data/IC9600/train_caption.txt"       # Training annotation file (<image_name>  <score>  <caption>)
  val_file: "../data/IC9600/test_caption.txt"           # Validation annotation file
  img_dir: "../data/IC9600/images"           # Images directory
  max_length: 32                # Max caption token length
  image_size: 512               # Image size

# Model configuration
model:
  vision_model_name: "resnet18"
  text_model_name: "bert-base-uncased"
  hidden_dim: 512               # Fusion layer hidden dimension
  pretrained: true              # Whether to use pretrained weights
  use_icnet_head: true          # Use ICNetHead instead of simple FC head

# Training configuration
train:
  device: "cuda"                # cuda or cpu
  batch_size: 16

  epochs: 30
  warm: 1                       # Warm-up epochs

  lr: 0.05                      # Initial learning rate
  lr_decay_rate: 0.2            # Learning rate decay rate
  weight_decay: 0.0001          # L2 regularization
  milestones: [10, 20]          # Learning rate milestones

  lambda: 0.0000                # Information bottleneck weight

  save_interval: 10             # Interval (epochs) to save checkpoints
  checkpoint_dir: "checkpoints" # Checkpoint directory

# Validation configuration
val:
  batch_size: 32
  checkpoint: "fusion_regressor.pth"  # Checkpoint path
